# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

install:
    - cp website/settings/local-travis.py website/settings/local.py
    - pip install -r requirements.txt

script: py.test
